### ISSUE TITLE
Negative data values in dashboard

### ISSUE THREAD

**Issue by ZF-fredericvanlinthoudt** [kyverno/grafana-dashboard#15]
Hi,

Since [this commit](https://github.com/kyverno/grafana-dashboard/commit/b77af3fee383a95cef75a10824046b721166debd), we are seeing negative values in the dashboard that just don't make sense.

Further more the rule execution success rate / background-scans success rate were changed into failure rates but the threshold colors weren't changed to a low failure rate is showing in red but it should actually be green.

Screenshot:
<img width="3121" alt="Screenshot 2022-10-28 at 10 06 11" src="https://user-images.githubusercontent.com/74649673/198537145-9c81ac64-b7a6-478a-8b09-caa26bac9cd6.png">

**Comment by realshuting** [comment]
Could be related to https://github.com/kyverno/kyverno/issues/4898.

**Comment by realshuting** [comment]
Please verify the latest version in [kyverno/kyverno](https://github.com/kyverno/kyverno/blob/main/charts/kyverno/grafana/dashboard.json).

This repository is archived, please open a new issue in kyverno/kyverno if the issue still exists.
